### ISSUE TITLE
Special character in *source* file

### ISSUE THREAD

**Issue by sirikid** [ichernyshovvv/completing-read-strings#1]
https://github.com/ichernyshovvv/completing-read-strings/blob/d10f63bfcf3644f692ccad095cce42b21e15466d/completing-read-strings.el#L102

should be `?\C-m` or `?\^M`

**Comment by ichernyshovvv** [comment]
Fixed with https://github.com/ichernyshovvv/completing-read-strings/commit/e55a5d62c0f8cd779f6fd636ed9530d118f6f900. Thanks.
